### PR TITLE
WIP Footer fix

### PR DESCRIPTION
**Pull request by Unesdala**
Playing around with styling to finally fix the footer.

Needs to have different spacing for a few different view ports still (To fix issues with pages that aren't 404 but are blank.) And to fine tune the exact spacing.

### CODE REVIEW

**Comment by JoshuaVSherman** [comment]
@Unesdala any progress on this yet!?

**Comment by JoshuaVSherman** [comment]
@Unesdala is this ready for me to review again now?

**Comment by JoshuaVSherman** [comment]
@Unesdala it says there are merge conflicts, please fix those and push up the changes

**Comment by JoshuaVSherman** [comment]
@Unesdala is this ready for me to review now?

**Comment by Unesdala** [comment]
Don't know if the changes I made are enough to fix what you were showing, but without knowing the specifics of what's causing it, and not being able to recreate it, yes.

**Comment by JoshuaVSherman** [comment]
@Unesdala is this one ready yet please?

**Pull request merged**
