### PR TITLE
WIP Music dashboard clock input

### PR DESCRIPTION
**Pull request by Unesdala**
Time isn't passing into the form properly.

### CODE REVIEW

**Comment by Unesdala** [comment]
@JoshuaVSherman - any idea how you'd pass state from timeKeeper back to the dashboard, given it's using hooks?

**Comment by JoshuaVSherman** [comment]
You can set the on change to be the set state of the dashboard

**Comment by JoshuaVSherman** [comment]
@Unesdala I just updated dev branch again, finishes unit tests and codeclimate

**Comment by Unesdala** [comment]
@JoshuaVSherman - Not sure how to test for the last couple lines.

Can you use the equivalent of what the hooks would be, or would you have to use a library that can test for hooks, since enzyme isn't able to yet?

onDoneClick might be tricky too - the way they formatted the done button is wonky. It's a span, not a button itself. And (assuming) using JS to close it all - So don't know if simulating a button click would work all the same with it. Other one should, given it's a proper button, but.

**Pull request merged**
