### PR TITLE
Test

### PR DESCRIPTION
**Pull request by DannyMcwaves**
Set up react project.
Remove some aurelia dependencies and the aurelia framework.

#2

### CODE REVIEW

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman can you review this and merge

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves as an option for the icons, if it would be easier (and in this case I don't mind if they are not exactly matching), consider using these packages:

    "@fortawesome/fontawesome-svg-core": "^1.2.12",
    "@fortawesome/free-regular-svg-icons": "^5.6.3",
    "@fortawesome/free-solid-svg-icons": "^5.6.3",
    "@fortawesome/react-fontawesome": "^0.1.3",

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman requested fixes have been taken care of.

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves almost done, few things left to fix please:

* mobile menu toggle is missing the black background on the icon:
image

* scrollbar should not display over the header
image

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves also, hard code the 'click here to listen' link to open https://web-jam.com/music/originals
for now (i'll fix it with env vars later when I get it running with the backend)

thanks

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves lastly, please add these nav links to the side menu that just link directly to 
http://web-jam.com/music/<that page> and the homepage

image

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman Fixes made.

**Pull request merged**
